# -*- coding: utf-8 -*-
"""testOnly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozJ4yQ0TrHCDKAJ0ZFFxctCIGwHMFNTg

**Connect with Google drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Augmentation part**"""

import cv2
import os
from skimage.io import imread, imshow
from PIL import Image
import tensorflow as tf
from tensorflow import keras

def augment(image):
  image = tf.image.random_brightness(image, 0.1)
  image = tf.image.random_contrast(image,0.7,1.3)
  
  image = tf.image.random_hue(image,0.005)
  image = tf.image.random_saturation(image,0.8, 1.3)

  image = tf.image.adjust_gamma(image,1)
  image = tf.image.random_flip_left_right(image)
  image = tf.image.random_flip_up_down(image)
  return image

#Path that you want to augment
path = '/content/drive/MyDrive/Dataset/Train/Glaucoma'

folders = os.listdir(path)

for folder_name in folders:
    files = os.listdir(path+'/'+ folder_name)
    for file_name in files:
        img = cv2.imread(path+'/'+ folder_name + '/'+file_name)

        for i in range(1):
          cv2.imwrite(path+'/'+folder_name+'/'+file_name[:file_name.index('.')]+'_augmented'+str(i+1)+file_name[file_name.index('.'):], augment(img).numpy())
        

        



print("finish")